---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-23/ee-supported-rhel8:1.0.0-597'
    
dependencies:
  system: bindep.txt
  python: requirements.txt
  galaxy: requirements.yml
additional_build_steps:
  prepend: |
    RUN whoami
    RUN cat /etc/os-release
  append:
    - RUN echo This is a post-install command0
    - RUN ls -la /etc
