---

- name: Get Local Hostname

  hosts: localhost

  gather_facts: yes  # This is essential to gather system facts, including the hostname



  tasks:

    - name: Display the hostname

      debug:

        msg: "The hostname of the localhost is {{ ansible_facts['hostname'] }}"
