---
# tasks file for create_azure_media
- name: Ensure destination directory exists
  file:
    path: /mnt/iso
    state: directory
  run_once: true

- name: Mount DVD read-only
  ansible.posix.mount:
    path: /mnt/iso
    src: /opt/SharkCage/AzureStackHCI_20349.1607_en-us.iso
    fstype: iso9660
    opts: ro,noauto,loop
    state: ephemeral
  run_once: true
  become: true

- name: Ensure destination directory is gone
  file:
    path: /tmp/AzureStackHCI
    state: absent
  run_once: true

- name: Ensure destination directory exists
  file:
    path: /tmp/AzureStackHCI
    state: directory
  run_once: true

- name: Copy the contents of the ISO to the target directory
  shell: cp -R /mnt/iso/* /tmp/AzureStackHCI/
  run_once: true

- name: Unmount DVD
  ansible.posix.mount:
    path: /mnt/iso
    src: /opt/SharkCage/AzureStackHCI_20349.1607_en-us.iso
    fstype: iso9660
    opts: ro,noauto
    state: absent
  run_once: true

- name: Create Azure Stack HCI Autounattend.xml
  template:
    src: templates/Autounattend.xml.j2
    dest: /tmp/AzureStackHCI/Autounattend.xml

- name: Remove old ISO if it exists
  file:
    path: "/opt/SharkCage/{{inventory_hostname}}_media.iso"
    state: absent

- name: Generate ISO image
  command: |
    genisoimage -relaxed-filenames -J -R \
    -o '/opt/SharkCage/{{inventory_hostname}}_media.iso' \
    -b boot/etfsboot.com \
    -c BOOT.CAT \
    -no-emul-boot \
    -boot-load-size 4 \
    -boot-info-table \
    -eltorito-alt-boot \
    -e efi/microsoft/boot/efisys.bin \
    -no-emul-boot '/tmp/AzureStackHCI'
