---
# tasks file for create_azure_media
- name: Ensure destination directory exists
  file:
    path: /mnt/iso
    state: directory
  when: inventory_hostname == 'hv01'

- name: Generate ISO image
  command: |
    mount -o loop /opt/SharkCage/AzureStackHCI_20349.1607_en-us.iso /mnt/iso
  when: inventory_hostname == 'hv01'

- name: Ensure destination directory is gone
  file:
    path: /tmp/AzureStackHCI
    state: absent
  when: inventory_hostname == 'hv01'

- name: Ensure destination directory exists
  file:
    path: /tmp/AzureStackHCI
    state: directory
  when: inventory_hostname == 'hv01'

- name: Copy the contents of the ISO to the target directory
  shell: cp -R /mnt/iso/* /tmp/AzureStackHCI/
  when: inventory_hostname == 'hv01'

- name: Unmount DVD
  ansible.posix.mount:
    path: /mnt/iso
    src: /opt/SharkCage/AzureStackHCI_20349.1607_en-us.iso
    fstype: iso9660
    opts: ro,noauto
    state: absent
  when: inventory_hostname == 'hv01'

- name: Create Azure Stack HCI Autounattend.xml
  template:
    src: templates/Autounattend.xml.j2
    dest: /tmp/AzureStackHCI/Autounattend.xml

- name: Remove old ISO if it exists
  file:
    path: "/opt/SharkCage/{{inventory_hostname}}_media.iso"
    state: absent

- name: Generate ISO image
  command: |
    genisoimage \
    -b boot/etfsboot.com \
    -no-emul-boot \
    -c BOOT.CAT \
    -iso-level 4 \
    -J \
    -l \
    -D \
    -N \
    -joliet-long \
    -relaxed-filenames \
    -v \
    -V "Custom" \
    -udf \
    -boot-info-table \
    -eltorito-alt-boot \
    -eltorito-boot efi/microsoft/boot/efisys_noprompt.bin \
    -no-emul-boot \
    -o '/opt/SharkCage/{{ inventory_hostname }}_media.iso' \
    -allow-limited-size '/tmp/AzureStackHCI'